name: Run ls from starter workflow

on:
  workflow_call:
    inputs:
      app_name:
      type: string
      required: false
      branch:
        type: string
        required: true
        
jobs:
  - name: 
