name: Check file structure and variable from Starter workflow
# Being shown in actions right side
run-name: Executor

on:
  workflow_call:
    inputs:
      app_name:
        type: string
        required: false
      branch:
        type: string
        required: true
      ARTIFACT-NAME:
        type: string
        required: true

jobs:
  print_file_structure:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.ARTIFACT-NAME }}
          
      - name: Check file structure in the reusable workflow
        run: ls -lha
   
  print_var:
    runs-on: ubuntu-latest
    steps:
      - name: print branch var
        run: echo ${{ inputs.branch }}
        
      - name: print app_name var
        run: echo ${{ inputs.app_name }}
        
      - name: print ARTIFACT-NAME var
        run: echo ${{ inputs.ARTIFACT-NAME }}
