name: Runs from the starter workflow
on:
  workflow_call:
    inputs:
      app_name:
        type: string
        required: false
      branch:
        type: string
        required: true
jobs:
  print_file_structure:
    runs-on: ubuntu-latest
    steps:
      - name: ls -lha
        run: ls -lha
   
  print_var:
    runs-on: ubuntu-latest
    steps:
      - name: print var
        run: echo ${{ inputs.branch }}
