name: Test repo and var pass to reusable workflow

env:
  VAR: "MAIN"

on: 
  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: main

jobs:
  checkout_and_make_changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout from specified branch
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}
        fetch-depth: 0
    - name: Changing some files
      run: touch file_created_during_workflow
      
    - name: ls -lha
      run: ls -lha
      
    - name: Create artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: change_from_workflow
      
  print_file_structure:
    runs-on: ubuntu-latest
    needs: checkout_and_make_changes
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          
      - name: ls -lha
        run: ls -lha
        
  check:   
    uses: lepkov/Test-Reusable-Actions-04/.github/workflows/check.yml@main
    needs: [checkout_and_make_changes]
    secrets: inherit
    with:
      app_name: ${{ github.event.repository.name }}
      branch: ${{ inputs.branch }}
    
