name: Test repo and var pass to reusable workflow
# Being shown in actions right side
run-name: Starter
# Никаких -, только _
env:
  VAR: "MAIN"
  ARTIFACT_NAME: "my-artifact"

on: 
  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: main

jobs:
  checkout_and_make_changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout from specified branch
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}
        fetch-depth: 0
        
    - name: Create a file to check
      run: touch file_created_during_workflow
      
    # Без него не работает передача артефакта
    - name: Create a file to store artifact
      run: touch change_from_workflow
      
    - name: Check file structure inside the job
      run: ls -lha
      
    - name: Create artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: change_from_workflow
      
  print_file_structure:
    runs-on: ubuntu-latest
    needs: checkout_and_make_changes
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          
      - name: Check file structure in another job
        run: ls -lha
        
  check:   
    uses: lepkov/Test-Reusable-Actions-04/.github/workflows/check.yml@main
    needs: [checkout_and_make_changes]
    secrets: inherit
    env: # Define the environment variable here
    ARTIFACT_NAME: ${{ env.ARTIFACT_NAME }}
    with:
      app_name: ${{ github.event.repository.name }}
      branch: ${{ inputs.branch }}
      ARTIFACT_NAME: ${{ env.ARTIFACT_NAME }}
      
  delete_artifact:
    runs-on: ubuntu-latest
    needs: [print_file_structure, check]
    steps:
      - uses: geekyeggo/delete-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
    
