name: Test repo and var pass to reusable workflow
# Глобальные энв варс, доступные всем джобам
env:
  VAR: "MAIN"
  # вcтавляем номер коммита в переменную 

on: 
  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: main

# Каждый джоб запускается в отдельном контейнере и ПАРАЛЛЕЛЬНО с другими
jobs:
  checkout_and_make_changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout from specified branch
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}
        fetch-depth: 0
    - name: Changing some files
      run: touch change_from_workflow
      
  print_file_structure:
    runs-on: ubuntu-latest
    steps:
      - name: ls -lha
        run: ls -lha
        
  check:   
    uses: lepkov/Test-Reusable-Actions-04/.github/workflows/check.yml@main
    needs: [checkout_and_make_changes]
    secrets: inherit
    with:
      app_name: ${{ github.event.repository.name }}
      branch: ${{ inputs.branch }}
    
