name: Test repo and var pass to reusable workflow
# Глобальные энв варс, доступные всем джобам
env:
  VAR: "MAIN"
  # вcтавляем номер коммита в переменную 

on: 
  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: main

# Каждый джоб запускается в отдельном контейнере и ПАРАЛЛЕЛЬНО с другими
jobs:
  checkout_and_make_changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout from specified branch
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}
        fetch-depth: 0
    - name: Changing some files
      run: touch change_from_workflow
    # Передаём в другую джобу репозиторий
    - name: Cache node modules
      uses: actions/cache@v2        
      with:
        # A directory to store and save the cache
        path: .
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-root
      
  print_file_structure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: prime-numbers
          key: ${{ runner.os }}-root
      - name: ls -lha
        run: ls -lha
        
  check:   
    uses: lepkov/Test-Reusable-Actions-04/.github/workflows/check.yml@main
    needs: [checkout_and_make_changes]
    secrets: inherit
    with:
      app_name: ${{ github.event.repository.name }}
      branch: ${{ inputs.branch }}
    
